### ISSUE TITLE
Helm buildchain does fail with dependencies

### ISSUE THREAD

**Issue by Deaddy** [Sciebo-RDS/charts#4]
**Describe the bug**

When using the official helm repo, you see some errors with templates not existing.
This seems to be related to missing dependencies.

**To Reproduce**
1. helm repo up
2. helm install sciebords sciebords/all

**Workaround**
1. git clone https://github.com/Sciebo-RDS/Sciebo-RDS.git
2. cd Sciebo-RDS/charts
3. for each chart cd $chart helm dep update
4. helm install sciebords $pathto-local-helm-chart

**Additional context**

**Comment by Deaddy** [comment]
We are now in the fortunate situation to actually test this;
both SURF and SUNET and we can template/deploy fine from the git cloned repo after running the `helm dep update` and `helm dep build` in each folder, but when using the helm repo at harbor we get
```
$ helm template rds/all  --values ~/applications/rds-test/values.yml 
Error: template: all/charts/layer3-token-storage/templates/_helpers.tpl:11:3: executing "layer3_token_storage.image" at <include "common.image" (dict "imageRoot" .Values.image "global" .Values.global)>: error calling include: template: no template "common.image" associated with template "gotpl
```

Something in our buildstep is missing; possibly we can copy from other internal ci templates.

**Comment by jakdimi** [comment]
The order in which the commands are executed are at fault, recreate the error locally:
```
for d in charts/*/  ; do
  helm dependency update $d
  helm dependency build $d
  helm package $d
done
helm template ./all-0.2.10.tgz
```

This is actually the order in which we build the packages.

**Comment by jakdimi** [comment]
```
for f in ./*tgz ; do
  rm $f
done

for d in charts/*/ ; do
  rm -rf $d/charts
done

git restore .

for d in charts/*/ ; do
  helm dependency update "${d}"
done

for d in charts/*/ ; do
  helm dependency build "${d}"
done

for d in charts/*/ ; do
  helm package "${d}"
done
```
does it, but it does not seem to work in gitlab-ci, maybe we need to delete all dependencies before updating

**Comment by Deaddy** [comment]
I think this has been fixed with your new ci script
